// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHCOLV99lIoW8NVTKLP1N4AFRTB5ApKHM',
    appId: '1:370086964182:web:ea9be0ddc1bb1d063ed277',
    messagingSenderId: '370086964182',
    projectId: 'wo-app-5ed20',
    authDomain: 'wo-app-5ed20.firebaseapp.com',
    storageBucket: 'wo-app-5ed20.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNrdIVnOygkbbj28YQz4kGwqmLL1ro2z0',
    appId: '1:370086964182:android:bd24a9e998c9d36e3ed277',
    messagingSenderId: '370086964182',
    projectId: 'wo-app-5ed20',
    storageBucket: 'wo-app-5ed20.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9gUm-t81k7gthlllA5uyroxGlrVZZBUw',
    appId: '1:370086964182:ios:3129c30747d3c9253ed277',
    messagingSenderId: '370086964182',
    projectId: 'wo-app-5ed20',
    storageBucket: 'wo-app-5ed20.firebasestorage.app',
    iosBundleId: 'com.example.wo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9gUm-t81k7gthlllA5uyroxGlrVZZBUw',
    appId: '1:370086964182:ios:3129c30747d3c9253ed277',
    messagingSenderId: '370086964182',
    projectId: 'wo-app-5ed20',
    storageBucket: 'wo-app-5ed20.firebasestorage.app',
    iosBundleId: 'com.example.wo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHCOLV99lIoW8NVTKLP1N4AFRTB5ApKHM',
    appId: '1:370086964182:web:ee4fb0f4f7810a323ed277',
    messagingSenderId: '370086964182',
    projectId: 'wo-app-5ed20',
    authDomain: 'wo-app-5ed20.firebaseapp.com',
    storageBucket: 'wo-app-5ed20.firebasestorage.app',
  );
}
